import type {Metadata} from "next";
import "./globals.css";

import {Cinzel, Poppins} from "next/font/google";

const primary = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-primary",
});

const secondary = Cinzel({
  subsets: ["latin"],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${primary.variable} ${secondary.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
